version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    working_directory: /android-sdk
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Docker image
          command: |
            TAG=1.2.$CIRCLE_BUILD_NUM
            docker build -t drazisil/android-sdk:$TAG .
      - run:
          name: Test Docker image
          command: ./test.sh
          #      - run:
          #name: Push Docker image
          #command: ./deploy.sh
