version: 2
jobs:
  build:
    docker:
      - image: golang:1.6.4
    working_directory: /android-sdk
    steps:
      # Ensure your image has git, otherwise the checkout step will fail
      # - run: apt-get -qq update; apt-get -y install git
      - checkout
      - setup_docker_engine
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: |
            TAG=1.2.$CIRCLE_BUILD_NUM
            docker build -t drazisil/android-sdk:$TAG .
      - run:
          name: Test Docker image
          command: ./test.sh
      - run:
          name: Push Docker image
          command: ./deploy.sh
